"""empty message

Revision ID: 7ecc9a28f3f2
Revises: da96e85e603c
Create Date: 2019-10-27 23:49:08.254911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecc9a28f3f2'
down_revision = 'da96e85e603c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_talent', new_column_name='seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue', new_column_name='seeking_talent')
    # ### end Alembic commands ###
